### ISSUE TITLE
[Suggestion] - Latest mako with lower PHP version

### ISSUE THREAD

**Issue by ConsoleTVs** [mako-framework/framework#140]
Hello, as a suggestion after using some php frameworks is to work in a lower php version, and for this I dont mean to use the early mako versions where the php is lower, what i do mean its much more simple, i know that some functions in the latest mako version use the php 5.5 functions of php, but i think the something can be done rather than just downgrade the mako version and be unable to use some functions ,such as route groups, just for having a lower php version

Please notice that most servers nowadays only have 5.4 as the latest version, and it's not my own case only, for this I mean, i have some friends that where forced to use another framwrork for this problem, and i consider mako to be one of the best right now.

What do you think ?

I am sure that something can be done to make that latest mako version work on a lower php version, such as 5.4 as most servers have. (even if some functions must be unable to use) like create

Mako: 4.4 for php 5.5 +

Mako 4.4 for php 5.4 +

**Comment by freost** [comment]
Hi,

PHP 5.4 has reached its EOL so I won't support it. It hasn't been supported since 14 Sep 2014 and will stop receiving security updates on 14 Sep 2015. Check out this page for more details http://php.net/supported-versions.php.

Hosting providers should upgrade to 5.6 or at least 5.5 in order to keep their clients secure.

I recommend using a VPS provider such as [Linode](https://www.linode.com/) where you can controll everything yourself.

**Comment by letr0n** [comment]
You also have [Digital Ocean](https://www.digitalocean.com) they have an awesome "one-click-app" install for the [LAMP platform](https://www.digitalocean.com/features/one-click-apps/lamp/).

**Comment by ConsoleTVs** [comment]
I agree about security stuff, i talked to my hosting providers and they saied that they will implement it soon but well.. who knows!

And most free hosting now se 5.4, that's why I saied it :p Thanks anyway!

I support +5.5 as well :)
