### ISSUE TITLE
Feature request: Support PSR-3's LoggerAwareInterface in the DI

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#217]
[PSR-3](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md) introduced the `LoggerInterface`, which is widely used, but also introduced the `LoggerAwareInterface`. This interface declares that the class knows of some kind of logger, and would like to have it injected.

It would be nice to have this feature in the DI container. The code (in the factory method) could be something like:

```php
if ($instance instanceof LoggerAwareInterface) {
    $instance->setLogger($this->resolveContextualParameter(get_class($instance), LoggerInterface::class));
}
```

I'd like to hear your opinion on this. If you agree, I could create an actual implementation and test case.

**Comment by freost** [comment]
I believe that this is something that should be implemented by overriding the container class.

I could probably move the [object creation](https://github.com/mako-framework/framework/blob/master/src/mako/application/Application.php#L458) into its own method (`createContainer`) so that less code would have to be duplicated when overriding it.

**Comment by freost** [comment]
Implemented [containerFactory](https://github.com/mako-framework/framework/blob/1c8db65845537e6d0053978a390e2b5ede1d33e8/src/mako/application/Application.php#L445) to make it easier to extend the container.
