### ISSUE TITLE
Error cannot save empty instance of model to database

### ISSUE THREAD

**Issue by mathysie** [mako-framework/framework#228]
I wrote a sqlite-table 'clicks' the following way:
<pre>
CREATE TABLE clicks (
	id   INTEGER 	PRIMARY KEY,
	time TIMESTAMP 	NOT NULL DEFAULT CURRENT_TIMESTAMP
);
</pre>
In my controller the line `$click = (new Click())->save();` generates <pre>SQLSTATE[HY000]: General error: 1 near ")": syntax error [ INSERT INTO "clicks" () VALUES () ] </pre>
Model Click only consists of only one method `protected $tableName = 'clicks';`.

It would seem saving a click this way should be possible, since mako generates the `id` and the `time` is added in by default.

**Comment by freost** [comment]
The id is not generated by mako unless you configure your model to use `PRIMARY_KEY_TYPE_UUID ` or `PRIMARY_KEY_TYPE_CUSTOM `.

A temporary workaround for inserting a row with no values while using a normal auto incrementing id would be to use the [`TimestampedTrait`](https://makoframework.com/docs/5.2/databases-sql:orm#traits:timestamped) since it will automatically generate the datetime values for you.

**Comment by freost** [comment]
I have added support for inserting "empty" rows (bc1d7d5e88a0beda2a4e8c60f4954376e283536e) but I haven't tagged a release yet.

**Comment by freost** [comment]
Fixed in 5.2.5

**Comment by mathysie** [comment]
Thanks!
