### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SerjoA** [mako-framework/framework#289]
hi there
any showcases or benchmarks available?

**Comment by freost** [comment]
Hi,

There are no official benchmarks since the usual "Hello, world" benchmarks are not at good indication of how a real application will perform under load. But I have worked an app (that performs database queries, data transformation and view rendering) that stayed very performant while running on a single server with over 10k concurrent users.

**Comment by SerjoA** [comment]
thank you very much for the info
